<?php

/**
 * BaseRegion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $region
 * @property text $descripcion
 * @property Doctrine_Collection $UDTs
 * 
 * @method varchar             getRegion()      Returns the current record's "region" value
 * @method text                getDescripcion() Returns the current record's "descripcion" value
 * @method Doctrine_Collection getUDTs()        Returns the current record's "UDTs" collection
 * @method Region              setRegion()      Sets the current record's "region" value
 * @method Region              setDescripcion() Sets the current record's "descripcion" value
 * @method Region              setUDTs()        Sets the current record's "UDTs" collection
 * 
 * @package    obras
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('region');
        $this->hasColumn('region', 'varchar', 200, array(
             'type' => 'varchar',
             'length' => 200,
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Udt as UDTs', array(
             'local' => 'id',
             'foreign' => 'region_id'));
    }
}