<?php

/**
 * BaseTipoDeObra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $tipo_de_obra
 * @property text $descripcion
 * @property Doctrine_Collection $Obras
 * 
 * @method varchar             getTipoDeObra()   Returns the current record's "tipo_de_obra" value
 * @method text                getDescripcion()  Returns the current record's "descripcion" value
 * @method Doctrine_Collection getObras()        Returns the current record's "Obras" collection
 * @method TipoDeObra          setTipoDeObra()   Sets the current record's "tipo_de_obra" value
 * @method TipoDeObra          setDescripcion()  Sets the current record's "descripcion" value
 * @method TipoDeObra          setObras()        Sets the current record's "Obras" collection
 * 
 * @package    obras
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoDeObra extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_de_obra');
        $this->hasColumn('tipo_de_obra', 'varchar', 200, array(
             'type' => 'varchar',
             'length' => 200,
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Obra as Obras', array(
             'local' => 'id',
             'foreign' => 'tipo_obra_id'));
    }
}