<?php

/**
 * BasePrograma
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $programa
 * @property text $descripcion
 * @property integer $fuente_financ_id
 * @property FuenteFinanciamiento $FuenteFinanciamiento
 * @property Doctrine_Collection $Obras
 * 
 * @method varchar              getPrograma()             Returns the current record's "programa" value
 * @method text                 getDescripcion()          Returns the current record's "descripcion" value
 * @method integer              getFuenteFinancId()       Returns the current record's "fuente_financ_id" value
 * @method FuenteFinanciamiento getFuenteFinanciamiento() Returns the current record's "FuenteFinanciamiento" value
 * @method Doctrine_Collection  getObras()                Returns the current record's "Obras" collection
 * @method Programa             setPrograma()             Sets the current record's "programa" value
 * @method Programa             setDescripcion()          Sets the current record's "descripcion" value
 * @method Programa             setFuenteFinancId()       Sets the current record's "fuente_financ_id" value
 * @method Programa             setFuenteFinanciamiento() Sets the current record's "FuenteFinanciamiento" value
 * @method Programa             setObras()                Sets the current record's "Obras" collection
 * 
 * @package    obras
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePrograma extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('programa');
        $this->hasColumn('programa', 'varchar', 200, array(
             'type' => 'varchar',
             'length' => 200,
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('fuente_financ_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FuenteFinanciamiento', array(
             'local' => 'fuente_financ_id',
             'foreign' => 'id'));

        $this->hasMany('Obra as Obras', array(
             'local' => 'id',
             'foreign' => 'programa_id'));
    }
}