<?php

/**
 * BaseMunicipio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $departamento_id
 * @property integer $udt_id
 * @property varchar $municipio
 * @property text $descripcion
 * @property Udt $Udt
 * @property Departamento $Departamento
 * @property Doctrine_Collection $LineasObras
 * 
 * @method integer             getDepartamentoId()  Returns the current record's "departamento_id" value
 * @method integer             getUdtId()           Returns the current record's "udt_id" value
 * @method varchar             getMunicipio()       Returns the current record's "municipio" value
 * @method text                getDescripcion()     Returns the current record's "descripcion" value
 * @method Udt                 getUdt()             Returns the current record's "Udt" value
 * @method Departamento        getDepartamento()    Returns the current record's "Departamento" value
 * @method Doctrine_Collection getLineasObras()     Returns the current record's "LineasObras" collection
 * @method Municipio           setDepartamentoId()  Sets the current record's "departamento_id" value
 * @method Municipio           setUdtId()           Sets the current record's "udt_id" value
 * @method Municipio           setMunicipio()       Sets the current record's "municipio" value
 * @method Municipio           setDescripcion()     Sets the current record's "descripcion" value
 * @method Municipio           setUdt()             Sets the current record's "Udt" value
 * @method Municipio           setDepartamento()    Sets the current record's "Departamento" value
 * @method Municipio           setLineasObras()     Sets the current record's "LineasObras" collection
 * 
 * @package    obras
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMunicipio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('municipio');
        $this->hasColumn('departamento_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('udt_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('municipio', 'varchar', 200, array(
             'type' => 'varchar',
             'length' => 200,
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Udt', array(
             'local' => 'udt_id',
             'foreign' => 'id'));

        $this->hasOne('Departamento', array(
             'local' => 'departamento_id',
             'foreign' => 'id'));

        $this->hasMany('LineaObra as LineasObras', array(
             'local' => 'id',
             'foreign' => 'municipio_id'));
    }
}