<?php

/**
 * BaseUdt
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $region_id
 * @property integer $numero
 * @property text $descripcion
 * @property Region $Region
 * @property Doctrine_Collection $Municipios
 * @property Doctrine_Collection $LineasObras
 * 
 * @method integer             getRegionId()    Returns the current record's "region_id" value
 * @method integer             getNumero()      Returns the current record's "numero" value
 * @method text                getDescripcion() Returns the current record's "descripcion" value
 * @method Region              getRegion()      Returns the current record's "Region" value
 * @method Doctrine_Collection getMunicipios()  Returns the current record's "Municipios" collection
 * @method Doctrine_Collection getLineasObras() Returns the current record's "LineasObras" collection
 * @method Udt                 setRegionId()    Sets the current record's "region_id" value
 * @method Udt                 setNumero()      Sets the current record's "numero" value
 * @method Udt                 setDescripcion() Sets the current record's "descripcion" value
 * @method Udt                 setRegion()      Sets the current record's "Region" value
 * @method Udt                 setMunicipios()  Sets the current record's "Municipios" collection
 * @method Udt                 setLineasObras() Sets the current record's "LineasObras" collection
 * 
 * @package    obras
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUdt extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('udt');
        $this->hasColumn('region_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('numero', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Region', array(
             'local' => 'region_id',
             'foreign' => 'id'));

        $this->hasMany('Municipio as Municipios', array(
             'local' => 'id',
             'foreign' => 'udt_id'));

        $this->hasMany('LineaObra as LineasObras', array(
             'local' => 'id',
             'foreign' => 'udt_id'));
    }
}