<?php

/**
 * BaseLineaObra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $obra_id
 * @property varchar $ubicacion
 * @property integer $municipio_id
 * @property integer $udt_id
 * @property text $descripcion
 * @property float $costo_tramo
 * @property Municipio $Municipio
 * @property Udt $Udt
 * @property Obra $Obra
 * 
 * @method integer   getObraId()       Returns the current record's "obra_id" value
 * @method varchar   getUbicacion()    Returns the current record's "ubicacion" value
 * @method integer   getMunicipioId()  Returns the current record's "municipio_id" value
 * @method integer   getUdtId()        Returns the current record's "udt_id" value
 * @method text      getDescripcion()  Returns the current record's "descripcion" value
 * @method float     getCostoTramo()   Returns the current record's "costo_tramo" value
 * @method Municipio getMunicipio()    Returns the current record's "Municipio" value
 * @method Udt       getUdt()          Returns the current record's "Udt" value
 * @method Obra      getObra()         Returns the current record's "Obra" value
 * @method LineaObra setObraId()       Sets the current record's "obra_id" value
 * @method LineaObra setUbicacion()    Sets the current record's "ubicacion" value
 * @method LineaObra setMunicipioId()  Sets the current record's "municipio_id" value
 * @method LineaObra setUdtId()        Sets the current record's "udt_id" value
 * @method LineaObra setDescripcion()  Sets the current record's "descripcion" value
 * @method LineaObra setCostoTramo()   Sets the current record's "costo_tramo" value
 * @method LineaObra setMunicipio()    Sets the current record's "Municipio" value
 * @method LineaObra setUdt()          Sets the current record's "Udt" value
 * @method LineaObra setObra()         Sets the current record's "Obra" value
 * 
 * @package    obras
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLineaObra extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('linea_obra');
        $this->hasColumn('obra_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ubicacion', 'varchar', 50, array(
             'type' => 'varchar',
             'length' => 50,
             ));
        $this->hasColumn('municipio_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('udt_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('costo_tramo', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Municipio', array(
             'local' => 'municipio_id',
             'foreign' => 'id'));

        $this->hasOne('Udt', array(
             'local' => 'udt_id',
             'foreign' => 'id'));

        $this->hasOne('Obra', array(
             'local' => 'obra_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}