<?php

/**
 * BaseDepartamento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $provincia_id
 * @property varchar $departamento
 * @property text $descripcion
 * @property Provincia $Provincia
 * @property Doctrine_Collection $Municipios
 * 
 * @method integer             getProvinciaId()  Returns the current record's "provincia_id" value
 * @method varchar             getDepartamento() Returns the current record's "departamento" value
 * @method text                getDescripcion()  Returns the current record's "descripcion" value
 * @method Provincia           getProvincia()    Returns the current record's "Provincia" value
 * @method Doctrine_Collection getMunicipios()   Returns the current record's "Municipios" collection
 * @method Departamento        setProvinciaId()  Sets the current record's "provincia_id" value
 * @method Departamento        setDepartamento() Sets the current record's "departamento" value
 * @method Departamento        setDescripcion()  Sets the current record's "descripcion" value
 * @method Departamento        setProvincia()    Sets the current record's "Provincia" value
 * @method Departamento        setMunicipios()   Sets the current record's "Municipios" collection
 * 
 * @package    obras
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDepartamento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('departamento');
        $this->hasColumn('provincia_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('departamento', 'varchar', 200, array(
             'type' => 'varchar',
             'length' => 200,
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Provincia', array(
             'local' => 'provincia_id',
             'foreign' => 'id'));

        $this->hasMany('Municipio as Municipios', array(
             'local' => 'id',
             'foreign' => 'departamento_id'));
    }
}