<?php

/**
 * BaseUnidad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $unidad
 * @property text $descripcion
 * @property Doctrine_Collection $Obras
 * 
 * @method varchar             getUnidad()      Returns the current record's "unidad" value
 * @method text                getDescripcion() Returns the current record's "descripcion" value
 * @method Doctrine_Collection getObras()       Returns the current record's "Obras" collection
 * @method Unidad              setUnidad()      Sets the current record's "unidad" value
 * @method Unidad              setDescripcion() Sets the current record's "descripcion" value
 * @method Unidad              setObras()       Sets the current record's "Obras" collection
 * 
 * @package    obras
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUnidad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('unidad');
        $this->hasColumn('unidad', 'varchar', 200, array(
             'type' => 'varchar',
             'length' => 200,
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Obra as Obras', array(
             'local' => 'id',
             'foreign' => 'unidad_id'));
    }
}