<?php

/**
 * EstadoDeObraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadoDeObraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadoDeObraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstadoDeObra');
    }
  public function retrieveForSelectEstadoDeObra($q, $limit)
  {
    $q = Doctrine_Query::create()
                    ->from('EstadoDeObra')
                    ->where('estado_de_obra like ?', '%' . $q . '%')
//                    ->addOrderBy('estado_de_obra')
                    ->limit($limit);

    return $q->execute()->toKeyValueArray('id', 'estado_de_obra');
}
}