<?php

/**
 * FuenteFinanciamientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FuenteFinanciamientoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FuenteFinanciamientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FuenteFinanciamiento');
    }
}