<?php

/**
 * LineaObraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LineaObraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LineaObraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LineaObra');
    }
}