<?php

/**
 * MunicipioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MunicipioTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object MunicipioTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Municipio');
    }

    /**
     * @param <type> $q query
     * @param <type> $limit limite
     * @return <type> Retorna array para la acción AutocompleterMunicipio
     */
    public function retrieveForSelectMunicipio($q, $limit, $id_prov) {
        $q = Doctrine_Query::create()
                        ->from('Municipio m')
                        ->select('m.municipio, m.id')
                        ->leftJoin('m.Departamento d')
                        ->leftJoin('d.Provincia p')
                        ->where('p.id = ?', $id_prov)
                        ->andWhere('m.municipio ilike ?', '%' . $q . '%')
                        ->limit($limit);
        $municipios = $q->execute();
        $return = array();

        foreach ($municipios as $municipio) {
            $return[$municipio->getId()] = (string) $municipio->getMunicipio();
        }
        return $return;
    }

    public function retrieveUdtForSelectMunicipio($municipio_id) {
        $q = Doctrine_Query::create()
                        ->select('m.udt_id')
                        ->from('Municipio m')
                        ->where('m.id = ?', $municipio_id)
                        ->fetchOne();
        return $q;
    }

}