<?php

/**
 * ObraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Obra');
    }
}