<?php

/**
 * Obra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    obras
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Obra extends BaseObra {

    public function getTituloTipoDeObra() {
        return $this->getTipoDeObra()->getDescripcion();
    }
    public function getTituloEstadoObra() {
        return $this->getEstadoDeObra()->getEstadoDeObra();
    }

    public function save(Doctrine_Connection $conn = null) {
        $user_id = sfContext::getInstance()->getUser()->getGuardUser()->getId();
        if (is_null($this->getCreacion())) {
            $this->setCreacion($user_id);
        }
        $this->setEdicion($user_id);
        if (is_null($this->getOrganizacion())) {
            $this->setCreacion($user_id);
        }
        parent::save($conn);
    }

}
