<?php

/**
 * Obra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    obras
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Obra extends BaseObra {

    public function getTituloTipoDeObra() {
        return $this->getTipoDeObra()->getDescripcion();
    }

    public function getTituloEstadoObra() {
        return $this->getEstadoDeObra()->getEstadoDeObra();
    }

    public function save(Doctrine_Connection $conn = null) {
        $user_id = sfContext::getInstance()->getUser()->getGuardUser()->getId();
        $groups = sfContext::getInstance()->getUser()->getGuardUser()->getGroups();
        if($this->isNew()){
            $this->setCreacion($user_id);
            $this->setOrganizacion($groups[0]->getId());
        } else {
//            $this->setCreacion($this->getCreacion());
//            $this->setOrganizacion($this->getOrganizacion());
            echo $this->getCreacion();
            echo $this->getOrganizacion();
            die;

            $this->setEdicion($user_id);
        }
//        if ($this->getOrganizacion()==null) {
//
//        }
        return parent::save($conn);
    }


}
