<?php

/**
 * OrganismoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrganismoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrganismoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Organismo');
    }
}