<?php

/**
 * UnidadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnidadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnidadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Unidad');
    }
}