<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/02/13 07:12:46

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=obras',
  'username' => 'mr29a',
  'password' => 'dgbkof',
  'name' => 'doctrine',
)),);
