<?php
// auto-generated by sfViewConfigHandler
// date: 2012/02/10 22:20:34
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'newSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'editSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'newSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Nueva Obra', false, false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('../js/jquery-ui-1.8.16.custom/css/custom-theme/jquery-ui-1.8.16.custom.css', '', array ());
  $response->addStylesheet('menu.css', '', array ());
  $response->addStylesheet('formation.css', '', array ());
  $response->addStylesheet('obras.css', '', array ());
  $response->addJavascript('jquery-1.7.min.js', '', array ());
  $response->addJavascript('/js/jquery-ui-1.8.16.custom/js/jquery-ui-1.8.16.custom.min.js', '', array ());
  $response->addJavascript('double_list.js', '', array ());
  $response->addJavascript('lineasObrasForm.js', '', array ());
  $response->addJavascript('tabs_obras.js', '', array ());
  $response->addJavascript('formation.js', '', array ());
  $response->addJavascript('fuente_finac_form', '', array ());
  $response->addJavascript('programa_form.js', '', array ());
  $response->addJavascript('tipo_obra_form.js', '', array ());
  $response->addJavascript('empresa_form.js', '', array ());
  $response->addJavascript('organismo_form.js', '', array ());
  $response->addJavascript('vanadium.js', '', array ());
  $response->addJavascript('actualiza_monto.js', '', array ());
  $response->addJavascript('jquery.ui.datepicker.validation.js', '', array ());
  $response->addJavascript('ajax_municipio_udt', '', array ());
}
else if ($templateName.$this->viewName == 'editSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Editar Obra', false, false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('../js/jquery-ui-1.8.16.custom/css/custom-theme/jquery-ui-1.8.16.custom.css', '', array ());
  $response->addStylesheet('menu.css', '', array ());
  $response->addStylesheet('formation.css', '', array ());
  $response->addStylesheet('obras.css', '', array ());
  $response->addJavascript('jquery-1.7.min.js', '', array ());
  $response->addJavascript('/js/jquery-ui-1.8.16.custom/js/jquery-ui-1.8.16.custom.min.js', '', array ());
  $response->addJavascript('double_list.js', '', array ());
  $response->addJavascript('lineasObrasForm.js', '', array ());
  $response->addJavascript('tabs_obras.js', '', array ());
  $response->addJavascript('ajaxMunicipioUdt.js', '', array ());
  $response->addJavascript('formation.js', '', array ());
  $response->addJavascript('fuente_finac_form', '', array ());
  $response->addJavascript('programa_form.js', '', array ());
  $response->addJavascript('tipo_obra_form.js', '', array ());
  $response->addJavascript('empresa_form.js', '', array ());
  $response->addJavascript('organismo_form.js', '', array ());
  $response->addJavascript('vanadium.js', '', array ());
  $response->addJavascript('actualiza_monto.js', '', array ());
  $response->addJavascript('jquery.ui.datepicker.validation.js', '', array ());
}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('../js/jquery-ui-1.8.16.custom/css/custom-theme/jquery-ui-1.8.16.custom.css', '', array ());
  $response->addStylesheet('menu.css', '', array ());
  $response->addJavascript('jquery-1.7.min.js', '', array ());
  $response->addJavascript('/js/jquery-ui-1.8.16.custom/js/jquery-ui-1.8.16.custom.min.js', '', array ());
  $response->addJavascript('double_list.js', '', array ());
}

