generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardPermission
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_permission
    with_doctrine_route:   true

    config:
      fields:
        name: { label: Permiso }
        description: { label: Descripción }
        created_at: { label: Creado }
        updated_at: { label: Actualizado }
        users_list: { label: Lista de Usuarios }
        group_list: { label: Listado de Grupos }
      list:
        title: Listado de Permisos
        display: [=name, description, created_at, updated_at]

      edit:
        title: Editar el Permiso "%%name%%"

      new:
        title: Nuevo Permiso

      form:
        display: [name, description, groups_list, users_list]